#!/bin/bash -e
#
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#

buildId=$(date +"%Y-%m-%d_%H%M%S_%s")
timeEpoch=$(date +%s)
scriptName=`basename "$0"`
scriptPath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
quickSauceHome=$( echo "${scriptPath%/*}" )

source ${scriptPath}/start-000-piestry-base


# set default spec file
#[[ -z ${1} ]] || specFile="${1}"
#printf 'Using Spec File: %s\n' ${specFile}


# set default data centre
#[[ -z ${SAUCE_DC} ]] && SAUCE_DC="eu-central-1"
#printf 'Using Sauce data centre: %s\n' ${SAUCE_DC}


# set logger url
#userAuth="${SAUCE_USERNAME}:${SAUCE_ACCESS_KEY}"
#protoHost="https://${userAuth}@api.${SAUCE_DC}.saucelabs.com"
#baseURL="${protoHost}/api-testing/rest/v4/${SAUCE_API_PROJECT_HOOK_ID}"


# set project url
projectId=$(curl --location --silent --request GET ${baseURL} | jq --raw-output .id)
projectURL="https://app.${SAUCE_DC}.saucelabs.com/api-testing/project/${projectId}/logger"
printf "\nTransactions are availbe for review in the project logger.\n"
printf "URL: %s\n\n" ${projectURL}


# set options for m1 compatability
[[ $(uname -m) == "arm64" ]] && options="--platform linux/amd64"


# start piestry
read  -n 1 -p "Press return to start service."
printf 'Starting piestry in mocking mode with logger...\n'
docker run --rm --pull always ${options} \
    --volume "${quickSauceHome}/specs:/specs" \
    --publish 6000:5000 \
    quay.io/saucelabs/piestry \
    --validate-request \
    --validate-examples \
    -u /specs/${specFile} \
    --logger "${baseURL}/logger"
