#!/bin/bash -x
#
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#


# process captured responses
function text-to-json {
    for f in ls ${capturePath}/*.txt
    do
        filename=$(basename -- "$f")
        filename="${filename%.*}"
        j="${capturePath}/${filename}.json"
        jq '' ${f} > ${j}
        [[ ${?} == 0 ]] && rm ${f} || rm ${j}
    done
}

# check environment variables
[[ -z ${SAUCE_USERNAME} ]]  && printf 'Please set environment variable: SAUCE_USERNAME\nexiting...\n' && exit 4 
[[ -z ${SAUCE_ACCESS_KEY} ]] && printf 'Please set environment variable: SAUCE_ACCESS_KEY\nexiting...\n' && exit 4 
[[ -z ${SAUCE_API_PROJECT_HOOK_ID} ]] && printf 'Please set environment variable: SAUCE_API_PROJECT_HOOK_ID\nexiting...\n' && exit 4 


# set default data centre
[[ -z ${SAUCE_DC} ]] && SAUCE_DC="eu-central-1"
printf 'Using Sauce data centre: %s\n' ${SAUCE_DC}


# set logger url
userAuth="${SAUCE_USERNAME}:${SAUCE_ACCESS_KEY}"

protoHost="https://${userAuth}@api.${SAUCE_DC}.saucelabs.com"
hookUrl="${protoHost}/api-testing/rest/v4/${SAUCE_API_PROJECT_HOOK_ID}"

# set dashboard url
projectId=$(curl --location --silent --request GET ${hookUrl} | jq --raw-output .id)
projectUrl="https://app.${SAUCE_DC}.saucelabs.com/api-testing/project/${projectId}"
buildUrl="${projectUrl}/dashboard/logs?event=false&mode=all&build="${buildId}""
loggerUrl="${projectUrl}/logger"


# set docker options for m1 compatability
[[ $(uname -m) == "arm64" ]] && dockerOptions="--platform linux/amd64"