#!/bin/bash -e
#
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#

buildId=$(date +"%Y-%m-%d_%H%M%S_%s")
timeEpoch=$(date +%s)
scriptName=`basename "$0"`
scriptPath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
quickSauceHome=$( echo "${scriptPath%/*}" )

source ${scriptPath}/start-000-piestry-base

# print project url and capture path
function cleanup {
    printf "\n\n"
    printf "\nReview transactions at local path and in dashboard.\n"
    printf "path: %s\n\n" ${capturePath}
    printf "URL: %s\n\n" ${buildUrl}
}


trap cleanup EXIT


# make capture path
mkdir -p ${capturePath}
printf "\nTransactions will be captured locally.\n"
printf "path: %s\n\n" ${capturePath}


# print project build url
printf "\nTransactions are availbe for review in the project dashboard and filtered by build.\n"
printf "URL: %s\n\n" ${buildUrl}


# start piestry
[[ -z ${SAUCE_DEBUG} ]] && read  -n 1 -p "Press return to start service."
printf "Starting API mocking server in end-to-end mode.\n"
docker run --rm --pull always ${options} \
    --volume "${quickSauceHome}/specs:/specs" \
    --publish 6000:5000 \
    quay.io/saucelabs/piestry \
    --validate-request \
    --validate-examples \
    -u /specs/demo-api.yaml \
    --e2e --capture /${captureDir} \
    --logger "${hookUrl}/insights/events/_contract?buildId="${buildId}""