#!/bin/bash -x
#
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#


captureDir="specs/data/${buildId}"
capturePath="${quickSauceHome}/${captureDir}"

specFile="demo-api.yaml"


# check environment variables
[[ -z ${SAUCE_USERNAME} ]]  && printf 'Please set environment variable: SAUCE_USERNAME\nexiting...\n' && exit 4 
[[ -z ${SAUCE_ACCESS_KEY} ]] && printf 'Please set environment variable: SAUCE_ACCESS_KEY\nexiting...\n' && exit 4 
[[ -z ${SAUCE_API_PROJECT_HOOK_ID} ]] && printf 'Please set environment variable: SAUCE_API_PROJECT_HOOK_ID\nexiting...\n' && exit 4 


# set default spec file
[[ -z ${1} ]] || specFile="${1}"
printf 'Using Spec File: %s\n' ${specFile}


# set default data centre
[[ -z ${SAUCE_DC} ]] && SAUCE_DC="eu-central-1"
printf 'Using Sauce data centre: %s\n' ${SAUCE_DC}


# set logger url
userAuth="${SAUCE_USERNAME}:${SAUCE_ACCESS_KEY}"
protoHost="https://${userAuth}@api.${SAUCE_DC}.saucelabs.com"
baseURL="${protoHost}/api-testing/rest/v4/${SAUCE_API_PROJECT_HOOK_ID}"


# set options for m1 compatability
[[ $(uname -m) == "arm64" ]] && options="--platform linux/amd64"