#!/bin/bash -e
#
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#

buildId=$(date +"%Y-%m-%d_%H%M%S_%s")
timeEpoch=$(date +%s)
scriptName=`basename "$0"`
scriptPath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
quickSauceHome=$( echo "${scriptPath%/*}" )

source ${scriptPath}/start-000-sauce-base

# set default spec file, take 1st argument as spec if provided
specFile="demo-api.yaml"
printf 'Using Spec File: %s\n' ${specFile}


# print project url 
function cleanup {
    printf "\n\n"
    printf "\nReview transactions in the project logger.\n"
    printf "URL: %s\n\n" ${loggerUrl}
}

trap cleanup EXIT


# print project logger url
printf "\nTransactions are available for review in the project logger.\n"
printf "URL: %s\n\n" ${loggerUrl}


# start piestry
[[ -z ${SAUCE_DEBUG} ]] && read  -n 1 -p "Press return to start service."
printf 'Starting piestry in mocking mode with logger...\n'
docker run --rm --pull always ${dockerOptions} \
    --volume "${quickSauceHome}/specs:/specs" \
    --publish 6000:5000 \
    quay.io/saucelabs/piestry \
    --validate-request \
    --validate-examples \
    -u /specs/${specFile} \
    --logger "${hookUrl}/logger"
